### ISSUE TITLE
Publish app to Appstore

### ISSUE THREAD

**Issue by 3k** [brevansio/Kagi#4]
Hi, sorry this is not an actual issue. I just don't know how to connect with you. 
Do you planning to publish application in Appstore?

**Comment by brevansio** [comment]
Sorry for the late response. Yeah, I'm slowly getting there, but I wanted to add a few extra features not in the original repo before I do. Otherwise, it wouldn't be very different from the current MiniKeePass app.

**Comment by 3k** [comment]
Glad to hear that! Thank you.

**Comment by brevansio** [comment]
Sorry for the wait, but I finally got the app approved: 
https://apps.apple.com/us/app/kagi-keepass-password-manager/id1519974040
