### ISSUE TITLE
Touch ID not working as expected on launch.

### ISSUE THREAD

**Issue by alsmithson** [brevansio/Kagi#7]
It appears that TouchID won't work at all unless a PIN is enabled? It also seems that you have to turn on "remember database passwords." Doesn't "remember database passwords" allow Kagi to open a database without any user authentication?

1. Without a PIN enabled, I never get prompted for a TouchID when launching Kagi. I have to enter the database password every time.
2. Without "remember database passwords" enabled,  I never get prompted for a TouchID when launching Kagi. I have to enter the database password every time.
3. With PIN enabled and "remember database passwords" enabled, I have a problem at launch. most of the time I do not get a prompt for touchID, but do get a prompt for a PIN. Entering the PIN just gives me the ability to type in the password, no help at all. About every 3rd or 4th try, the TouchID prompt comes up for a fraction of a second; I am not fast enough to get my finger on the sensor. About 1 in 10 tries, the TouchID prompt stays up long enough for me to put my finger on the button and Kagi opens normally.
4. After about 20 launches, I tried turning off the PIN (left on "remember database passwords") and the next time I restarted Kagi, it opened the database without asking for a PIN or a touchID. That is a serious security problem.

I have an iPhoneSE (first edition) running IOS 14.6.

**Comment by alsmithson** [comment]
After about 30 launches, it seems to be working correctly now about 80% of the time. I installed it on an iPad Pro and it has worked just fine with FaceID (whatever it is called).

**Comment by brevansio** [comment]
#1 is something by design, but it does make sense to split those out.

The rest look like bugs, so I'll get to investigating and fixing them

**Comment by brevansio** [comment]
Should be fixed in the next App Store version (or current master)
