### ISSUE TITLE
UI Enhancement Requests

### ISSUE THREAD

**Issue by alsmithson** [brevansio/Kagi#8]
**1. Better defaults**

a. When adding a new entry, please do not autofill the title with"New Entry." Just leave it blank, or pre-highlight it so typing anything automatically deletes it. Every time I add an entry, Step #1 is to delete that default name, which is wasting time. 

b. When creating a new entry, please default to the key icon rather than a folder. The folder should be used for groups. If I don't remember to replace the default folder icon then my entries look like groups. KeePass used the key, but Mini KeePass switched to the folder which I think was a bad move and one that irritated me until the day Mini KeePass died. Most apps have fixed that issue and use keys for entries and folders for groups.

**2. Auto-save less often**

a. When creating a new entry please do not auto-save in the middle of the process. As soon as I click create new entry, there is a new entry (with that dreaded default title) added to the database. Hitting cancel does not cancel the operation as the New Entry is still there. Also, each time a change is made during creation, it gets synched back to the server (iCloud Drive in my case), just an unnecessary load on the network. Please wait for the Done button to be clicked before saving a new entry.

**Comment by brevansio** [comment]
Should be addressed in the next App Store version (or the current master).
