### ISSUE TITLE
Autofill Feature Requests

### ISSUE THREAD

**Issue by alsmithson** [brevansio/Kagi#9]
1. When using autofill, please use the last opened database. Having to choose a database every time slows things down. 
2. KeePass Touch and KeePassium do this and _also auto-select the matching entry_ which is a very nice feature. On the downside, KeePass Touch will not sync with iCloud Drive like Kagi Does, an KeePassium seems to cost a minimum of $15/year.

**Comment by brevansio** [comment]
Should be fixed in the next App Store Version (or current master)
